[workspace]
resolver = "2"
members = [
  "rush",
  "plugins/*",
  "rush-interface",
  "rush-macros",
  "rush-plugin",
]

[profile.release]
opt-level = 3
debug = false
strip = true
lto = "fat"
incremental = false
codegen-units = 1
